<?xml version="1.0"?>
<!--
  This file defines the core structure of the robot, including the chassis, wheels, and sensors.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Included files -->
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="common_properties.xacro"/>

    <!-- Material definitions -->
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->
    <!-- The base_link is the central reference frame for the robot. -->
    <link name="base_link">
    </link>

    <!-- BASE_FOOTPRINT LINK -->
    <!-- The base_footprint is located at the projection of the base_link on the ground. -->
    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 ${-wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- CHASSIS LINK -->
    <!-- The chassis is the main body of the robot. -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
        <!-- kp and kd for rubber -->
        <kp>1000000.0</kp> <!-- Contact stiffness -->
        <kd>100.0</kd>     <!-- Damping -->
        <mu1>1.0</mu1>     <!-- Friction coefficient -->
        <mu2>1.0</mu2>     <!-- Friction coefficient -->
        <fdir1>1 0 0</fdir1>
        <maxVel>1.0</maxVel>
        <minDepth>0.005</minDepth> <!-- Contacts gripping -->
    </gazebo>

    <!-- RIGHT WHEEL LINK -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
        <!-- kp and kd for rubber -->
        <kp>1000000.0</kp> <!-- Contact stiffness -->
        <kd>100.0</kd>     <!-- Damping -->
        <mu1>1.0</mu1>     <!-- Friction coefficient -->
        <mu2>1.0</mu2>     <!-- Friction coefficient -->
        <fdir1>1 0 0</fdir1>
        <maxVel>1.0</maxVel>
        <minDepth>0.005</minDepth> <!-- Contacts gripping -->
    </gazebo>


    <!-- CASTER WHEEL LINK -->
    <joint name="caster_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="${-caster_wheel_offset_x} 0 ${-caster_wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${wheel_thickness}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Gazebo simulation parameters for the caster wheel -->
    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <kp>1000000.0</kp>
        <kd>100.0</kd>
        <fdir1>1 0 0</fdir1>
        <maxVel>1.0</maxVel>
        <minDepth>0.0</minDepth>
        <mu1>0.0</mu1> <!-- Zero friction to prevent interference with robot motion -->
        <mu2>0.0</mu2> <!-- Zero friction to prevent interference with robot motion -->
    </gazebo>

</robot>